# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test01.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1905, 924)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_handPlate_takeGive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_handPlate_takeGive.setGeometry(QtCore.QRect(40, 680, 71, 41))
        self.pushButton_handPlate_takeGive.setObjectName("pushButton_handPlate_takeGive")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(-10, 0, 2301, 91))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 111, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_plates_servo_left = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_plates_servo_left.setObjectName("pushButton_plates_servo_left")
        self.verticalLayout.addWidget(self.pushButton_plates_servo_left)
        self.pushButton_plates_servo_right = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_plates_servo_right.setObjectName("pushButton_plates_servo_right")
        self.verticalLayout.addWidget(self.pushButton_plates_servo_right)
        self.pushButton_plates_up = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_plates_up.setObjectName("pushButton_plates_up")
        self.verticalLayout.addWidget(self.pushButton_plates_up)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 330, 111, 151))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.doubleSpinBox_Volt = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.doubleSpinBox_Volt.setObjectName("doubleSpinBox_Volt")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_Volt)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.doubleSpinBox_Current = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.doubleSpinBox_Current.setObjectName("doubleSpinBox_Current")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_Current)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.doubleSpinBox_TimeWorkPower = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.doubleSpinBox_TimeWorkPower.setObjectName("doubleSpinBox_TimeWorkPower")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_TimeWorkPower)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 500, 111, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.pushButton_mixer_up = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_mixer_up.setObjectName("pushButton_mixer_up")
        self.verticalLayout_2.addWidget(self.pushButton_mixer_up)
        self.pushButton_mixer_turn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_mixer_turn.setObjectName("pushButton_mixer_turn")
        self.verticalLayout_2.addWidget(self.pushButton_mixer_turn)
        self.pushButton_mixer_on = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_mixer_on.setObjectName("pushButton_mixer_on")
        self.verticalLayout_2.addWidget(self.pushButton_mixer_on)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 650, 91, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 90, 1911, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.pushButton_PowerSystem = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PowerSystem.setGeometry(QtCore.QRect(1770, 790, 91, 61))
        self.pushButton_PowerSystem.setObjectName("pushButton_PowerSystem")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.pushButton_handPlate_takeGive.setText(_translate("mainWindow", "Прием \n"
"Выдача"))
        self.pushButton_2.setText(_translate("mainWindow", "Файл"))
        self.pushButton_3.setText(_translate("mainWindow", "Помощь"))
        self.pushButton_4.setText(_translate("mainWindow", "Ручное упраление"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Положение <br/>пластин</span></p></body></html>"))
        self.pushButton_plates_servo_left.setText(_translate("mainWindow", "Влево "))
        self.pushButton_plates_servo_right.setText(_translate("mainWindow", "Вправо"))
        self.pushButton_plates_up.setText(_translate("mainWindow", "Подьем"))
        self.label_8.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Источник питания </p></body></html>"))
        self.label_4.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Напряжение</p></body></html>"))
        self.label_5.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Ток</p></body></html>"))
        self.label_11.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Время </p></body></html>"))
        self.label_3.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Мешалка раствора</p></body></html>"))
        self.pushButton_mixer_up.setText(_translate("mainWindow", "Подъем"))
        self.pushButton_mixer_turn.setText(_translate("mainWindow", "Поворот"))
        self.pushButton_mixer_on.setText(_translate("mainWindow", "Включение"))
        self.label_6.setText(_translate("mainWindow", "Захват пластины"))
        self.label_10.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Ручное упраление</span></p></body></html>"))
        self.pushButton_PowerSystem.setText(_translate("mainWindow", "Включить\n"
"Установку"))
